### ISSUE TITLE
Ops - Ansible: Common command for tasks

### ISSUE THREAD

**Issue by joelin109** [joelin109/blog#14]
## vars
```
    LocalPath: "/Volumes/Mac-TBD/Server/Python/server-api-py"
```
<br>

## tasks

- shell
```
 shell: pip show flask
 register: shell_result
 ignore_errors: True
```
<br>

- copy
```
template:
    src: "{{ LocalPath }}/conf/uwsgi.ini"
    dest: "{{ LocalPath }}/www"
    remote_src: yes
when: shell_result|success     #failed
notify:
        - handler name

# src: 是指该yml文件对应的路径 (本地)
```
<br>

- file
```
   - name: Delete or create file if already exists
      file:
        path: "{{ LocalPath }}/www/uwsgi.ini"
        state: "absent" # absent - delete, touch - create
        mode: "u+rw,g-wx,o-rwx"
      register: file_result
      ignore_errors: True

# create a directory if it doesn't exist
- file:
    path: /etc/some_directory
    state: directory
    mode: 0755
```
<br>

- service ?
```
-a 'name= state={started|stopped|restarted} enabled=(是否开机自动启动) runlevel='
[root@localhost ~]# ansible all -m service -a 'name=httpd state=started'
```
<br>

- script ?
```
-a '/PATH/TO/SCRIPT'运行脚本
[root@localhost ~]# ansible all -m script -a '/tmp/a.sh'
```
<br>

- cron ?
```
- name: Add cron job for 'storm recovery'
 cron: name="storm recovery" job="/usr/bin/storm-recovery" minute=*/5 state=present
 tags: guard

- name : remove 'storm recovery' cron entry
 cron :
   name  : storm recovery
   state : absent
```
<br>

- debug
```
 - debug: msg="{{ task_register.stdout }}"
 - debug: msg="{{ task_register.stdout_lines }}"
```
<br>

- with_items
```
    - debug: msg="item.item={{item}}"
      when: "{{item.find('requirements') >= 0}}"
      ignore_errors: True
      with_items: "{{git_ls.stdout_lines}}"
```
